"""Stage 5: actor-critic trained purely inside the learned world model.

The agent only ever sees rollouts generated by the frozen dynamics model; it
acts via the latent action codes discovered in Stage 2 and never touches the
real game. DreamerV3 machinery: symlog two-hot critic and reward, lambda
returns, EMA target critic, percentile return normalization. Policy gradients
are REINFORCE with the critic baseline (token states are discrete, so no
straight-through backprop through the dynamics).
"""

import copy

import torch
import torch.nn as nn

from models.heads import DistHead, PolicyHead, StateEncoder


class RewardModel(nn.Module):
    """Frame tokens -> predicted reward; trained on held-out TRUE rewards.

    This is the only place real-environment signal enters the agent stack —
    the plan's de-risking note applies: a wrong reward model dooms the agent,
    so check its accuracy before blaming the RL.
    """

    def __init__(self, vocab_size: int, tokens_per_frame: int = 64,
                 dim: int = 256, state_dim: int = 512, hidden: int = 512):
        super().__init__()
        self.encoder = StateEncoder(vocab_size, tokens_per_frame, dim, state_dim)
        self.head = DistHead(state_dim, hidden)

    def forward(self, tokens: torch.Tensor) -> torch.Tensor:
        return self.head(self.encoder(tokens))

    def predict(self, tokens: torch.Tensor) -> torch.Tensor:
        return self.head.mean(self(tokens))

    def loss(self, tokens: torch.Tensor, rewards: torch.Tensor) -> torch.Tensor:
        return self.head.loss(self(tokens), rewards)


class ImaginationAgent(nn.Module):
    """Policy + critic over single-frame token states."""

    def __init__(self, vocab_size: int, num_actions: int, tokens_per_frame: int = 64,
                 dim: int = 256, state_dim: int = 512, hidden: int = 512):
        super().__init__()
        self.encoder = StateEncoder(vocab_size, tokens_per_frame, dim, state_dim)
        self.actor = PolicyHead(state_dim, num_actions, hidden)
        self.critic = DistHead(state_dim, hidden)
        self.num_actions = num_actions

    def policy(self, tokens: torch.Tensor) -> torch.distributions.Categorical:
        return self.actor(self.encoder(tokens))

    def value(self, tokens: torch.Tensor) -> torch.Tensor:
        return self.critic(self.encoder(tokens))


def lambda_returns(rewards, values, bootstrap, gamma: float, lam: float):
    """R^l_t = r_t + g[(1-l)V_{t+1} + l R^l_{t+1}]; rewards/values (B, H)."""
    out = torch.zeros_like(rewards)
    nxt = bootstrap
    for t in reversed(range(rewards.shape[1])):
        v_next = values[:, t + 1] if t + 1 < values.shape[1] else bootstrap
        out[:, t] = rewards[:, t] + gamma * ((1 - lam) * v_next + lam * nxt)
        nxt = out[:, t]
    return out


class ImaginationTrainer:
    def __init__(self, dynamics, reward_model, agent, horizon: int = 15,
                 gamma: float = 0.985, lam: float = 0.95, entropy_coef: float = 3e-3,
                 actor_lr: float = 3e-5, critic_lr: float = 3e-5,
                 target_decay: float = 0.98, retnorm_decay: float = 0.99,
                 decode_steps: int = 4, device: str = "cpu"):
        self.dynamics = dynamics.eval().requires_grad_(False)
        self.reward_model = reward_model.eval().requires_grad_(False)
        self.agent = agent.to(device)
        self.target_critic = copy.deepcopy(agent.critic).requires_grad_(False)
        self.horizon, self.gamma, self.lam = horizon, gamma, lam
        self.entropy_coef, self.target_decay = entropy_coef, target_decay
        self.retnorm_decay, self.decode_steps, self.device = retnorm_decay, decode_steps, device
        self.actor_opt = torch.optim.Adam(
            list(agent.encoder.parameters()) + list(agent.actor.parameters()), lr=actor_lr
        )
        self.critic_opt = torch.optim.Adam(agent.critic.parameters(), lr=critic_lr)
        self.register_scale = torch.ones((), device=device)

    @torch.no_grad()
    def imagine(self, ctx: torch.Tensor, ctx_actions: torch.Tensor) -> dict:
        """Dream H steps from real context -> states/actions/rewards tensors."""
        states, actions, rewards = [], [], []
        cur_state = ctx[:, -1]
        for _ in range(self.horizon):
            a = self.agent.policy(cur_state).sample()
            nxt = self.dynamics.generate(ctx, ctx_actions, a, steps=self.decode_steps)
            r = self.reward_model.predict(nxt)
            states.append(cur_state)
            actions.append(a)
            rewards.append(r)
            ctx = torch.cat([ctx, nxt[:, None]], dim=1)[:, -self.dynamics.context_frames :]
            ctx_actions = torch.cat([ctx_actions, a[:, None]], dim=1)[:, -self.dynamics.context_frames :]
            cur_state = nxt
        return {
            "states": torch.stack(states, dim=1),  # (B, H, N)
            "actions": torch.stack(actions, dim=1),  # (B, H)
            "rewards": torch.stack(rewards, dim=1),  # (B, H)
            "final_state": cur_state,  # (B, N)
        }

    def update(self, ctx: torch.Tensor, ctx_actions: torch.Tensor) -> dict:
        rollout = self.imagine(ctx, ctx_actions)
        b, h, n = rollout["states"].shape
        flat = rollout["states"].reshape(b * h, n)

        with torch.no_grad():
            tgt_values = self.target_critic(self.agent.encoder(flat))
            tgt_values = self.target_critic.mean(tgt_values).reshape(b, h)
            bootstrap = self.target_critic.mean(
                self.target_critic(self.agent.encoder(rollout["final_state"]))
            )
            returns = lambda_returns(
                rollout["rewards"], tgt_values, bootstrap, self.gamma, self.lam
            )
            # DreamerV3 return normalization: 5th-95th percentile EMA scale
            spread = torch.quantile(returns, 0.95) - torch.quantile(returns, 0.05)
            self.register_scale.mul_(self.retnorm_decay).add_(
                spread * (1 - self.retnorm_decay)
            )
            advantage = (returns - tgt_values) / self.register_scale.clamp(min=1.0)

        dist = self.agent.policy(flat)
        logprob = dist.log_prob(rollout["actions"].reshape(-1)).reshape(b, h)
        entropy = dist.entropy().mean()
        actor_loss = -(logprob * advantage).mean() - self.entropy_coef * entropy
        self.actor_opt.zero_grad(set_to_none=True)
        actor_loss.backward()
        torch.nn.utils.clip_grad_norm_(
            list(self.agent.encoder.parameters()) + list(self.agent.actor.parameters()), 1.0
        )
        self.actor_opt.step()

        critic_logits = self.agent.critic(self.agent.encoder(flat).detach())
        critic_loss = self.agent.critic.loss(critic_logits, returns.reshape(-1))
        self.critic_opt.zero_grad(set_to_none=True)
        critic_loss.backward()
        torch.nn.utils.clip_grad_norm_(self.agent.critic.parameters(), 1.0)
        self.critic_opt.step()

        with torch.no_grad():
            for p, tp in zip(self.agent.critic.parameters(), self.target_critic.parameters()):
                tp.mul_(self.target_decay).add_(p, alpha=1 - self.target_decay)

        return {
            "actor_loss": actor_loss.item(),
            "critic_loss": critic_loss.item(),
            "entropy": entropy.item(),
            "imagined_return": returns.mean().item(),
            "imagined_reward": rollout["rewards"].mean().item(),
            "return_scale": self.register_scale.item(),
        }
